### ISSUE TITLE
Pallet generation issue using Python 3.10.12 for astropy

### ISSUE THREAD

**Issue by omaranwar85** [ICRAR/dlg_paletteGen#8]
I have both dependencies (doxygen and xsltproc) installed. dlg-paletteGen also installs without any issue. astropy-6.1.7 is also installed. Howeve while trying to generate the pallet for astropy, I get the following error (complete log)

dlg-paletteGen -rsSm astropy . .
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Recursive flag ON (cli.py:124)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Split flag ON (cli.py:130)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - PROJECT_NAME: daliuge (cli.py:272)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - PROJECT_VERSION: 0.1 (cli.py:273)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - GIT_REPO: daliuge (cli.py:274)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Input Directory: . (cli.py:276)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Tag:  (cli.py:277)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Output File: . (cli.py:278)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Allow missing EAGLE_START: True (cli.py:279)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Module Path: astropy (cli.py:280)
2024-12-12T11:33:43 - dlg_paletteGen.settings - INFO - Splitting module astropy into sub-module palettes: ['astropy', 'astropy.compiler_version', 'astropy.config', 'astropy.conftest', 'astropy.constants', 'astropy.convolution', 'astropy.coordinates', 'astropy.cosmology', 'astropy.extern', 'astropy.io', 'astropy.logger', 'astropy.modeling', 'astropy.nddata', 'astropy.samp', 'astropy.stats', 'astropy.table', 'astropy.time', 'astropy.timeseries', 'astropy.uncertainty', 'astropy.units', 'astropy.utils', 'astropy.version', 'astropy.visualization', 'astropy.wcs'] (cli.py:224)
Traceback (most recent call last):
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 362, in module_hook
    mod = eval(mod_name)
  File "<string>", line 1, in <module>
NameError: name 'astropy' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oanwar/daliuge/daliuge/bin/dlg-paletteGen", line 8, in <module>
    sys.exit(main())
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 287, in main
    palettes_from_module(
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 236, in palettes_from_module
    nodes, module_doc = nodes_from_module(m, recursive=top_recursive)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 180, in nodes_from_module
    modules, module_doc = module_hook(module_path, recursive=recursive)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 376, in module_hook
    members = get_members(
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 319, in get_members
    nodes = get_class_members(m, parent=parent)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 51, in get_class_members
    ann = inspect.get_annotations(
  File "/usr/lib/python3.10/inspect.py", line 175, in get_annotations
    return_value = {key:
  File "/usr/lib/python3.10/inspect.py", line 176, in <dictcomp>
    value if not isinstance(value, str) else eval(value, globals, locals)
  File "<string>", line 1, in <module>
NameError: name 'Callable' is not defined. Did you mean: 'callable'?

Here is the list of packages installed in the environment

```
Package                   Version             Editable project location
annotated-types           0.7.0
anyio                     4.7.0
anytree                   2.12.1
astroid                   3.3.6
astropy                   6.1.7
astropy-iers-data         0.2024.12.9.0.36.21
attrs                     24.2.0
bcrypt                    4.2.1
beautifulsoup4            4.12.3
BlockDAG                  1.1.0
boto3                     1.35.78
botocore                  1.35.78
bottle                    0.13.2
certifi                   2024.8.30
cffi                      1.17.1
charset-normalizer        3.4.0
click                     8.1.7
configobj                 5.0.9
crc32c                    2.7.1
cryptography              44.0.0
daliuge-common            4.8.0               /home/oanwar/daliuge/daliuge-common
daliuge-engine            4.8.0               /home/oanwar/daliuge/daliuge-engine
daliuge-translator        4.8.0               /home/oanwar/daliuge/daliuge-translator
dill                      0.3.9
dlg_paletteGen            0.3.10
docker                    7.1.0
et_xmlfile                2.0.0
exceptiongroup            1.2.2
fastapi                   0.115.6
ftfy                      6.3.1
future                    1.0.0
future-fstrings           1.2.0
gevent                    24.11.1
GPUtil                    1.4.0
greenlet                  3.1.1
h11                       0.14.0
idna                      3.10
ifaddr                    0.2.0
isort                     5.13.2
Jinja2                    3.1.4
jmespath                  1.0.1
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
lockfile                  0.12.2
mailchecker               6.0.13
MarkupSafe                3.0.2
mccabe                    0.7.0
merklelib                 1.0
metis                     0.2a5
msgpack                   1.1.0
netifaces                 0.11.0
networkx                  3.4.2
numpy                     2.2.0
openpyxl                  3.1.5
overrides                 7.7.0
packaging                 24.2
parameterized             0.9.0
paramiko                  3.5.0
phonenumbers              8.13.51
pip                       22.0.2
platformdirs              4.3.6
psutil                    6.1.0
pycparser                 2.22
pydantic                  2.10.3
pydantic_core             2.27.1
pyerfa                    2.0.1.5
pyext                     0.8
pylint                    3.3.2
PyNaCl                    1.5.0
pyswarm                   0.6
python-benedict           0.34.0
python-daemon             3.1.2
python-dateutil           2.9.0.post0
python-fsutil             0.14.1
python-multipart          0.0.19
python-slugify            8.0.4
PyYAML                    6.0.2
pyzmq                     25.1.1
referencing               0.35.1
requests                  2.32.3
rpds-py                   0.22.3
s3transfer                0.10.4
scp                       0.15.0
setuptools                59.6.0
six                       1.17.0
sniffio                   1.3.1
soupsieve                 2.6
starlette                 0.41.3
text-unidecode            1.3
toml                      0.10.2
tomli                     2.2.1
tomlkit                   0.13.2
typing_extensions         4.12.2
urllib3                   1.26.20
uvicorn                   0.18.0
wcwidth                   0.2.13
wheel                     0.45.1
xlrd                      2.0.1
xmltodict                 0.14.2
zeroconf                  0.38.4
zerorpc                   0.6.3
zope.event                5.0
zope.interface            7.2
```

**Comment by omaranwar85** [comment]
The numpy pallet was generated without any issues. So the above issue may be very specific to this version of astropy.

**Comment by omaranwar85** [comment]
I had issues with generating pallet for casacore as well. 

Switched to this branch
https://github.com/ICRAR/dlg_paletteGen/tree/parser_update

It worked for casacore, but still has the issue with astropy.

dlg-paletteGen -rsSm astropy . .
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Recursive flag ON (cli.py:124)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Split flag ON (cli.py:130)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - PROJECT_NAME: dlg_paletteGen (cli.py:272)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - PROJECT_VERSION: 0.1 (cli.py:273)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - GIT_REPO: dlg_paletteGen (cli.py:274)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Input Directory: . (cli.py:276)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Tag:  (cli.py:277)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Output File: . (cli.py:278)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Allow missing EAGLE_START: True (cli.py:279)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Module Path: astropy (cli.py:280)
2024-12-12T15:10:35 - dlg_paletteGen.settings - INFO - Splitting module astropy into sub-module palettes: ['astropy', 'astropy.compiler_version', 'astropy.config', 'astropy.conftest', 'astropy.constants', 'astropy.convolution', 'astropy.coordinates', 'astropy.cosmology', 'astropy.extern', 'astropy.io', 'astropy.logger', 'astropy.modeling', 'astropy.nddata', 'astropy.samp', 'astropy.stats', 'astropy.table', 'astropy.time', 'astropy.timeseries', 'astropy.uncertainty', 'astropy.units', 'astropy.utils', 'astropy.version', 'astropy.visualization', 'astropy.wcs'] (cli.py:224)
Traceback (most recent call last):
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 365, in module_hook
    mod = eval(mod_name)
  File "<string>", line 1, in <module>
NameError: name 'astropy' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oanwar/daliuge/daliuge/bin/dlg-paletteGen", line 33, in <module>
    sys.exit(load_entry_point('dlg-paletteGen==0.3.9', 'console_scripts', 'dlg-paletteGen')())
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 287, in main
    palettes_from_module(
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 236, in palettes_from_module
    nodes, module_doc = nodes_from_module(m, recursive=top_recursive)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/cli.py", line 180, in nodes_from_module
    modules, module_doc = module_hook(module_path, recursive=recursive)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 379, in module_hook
    members = get_members(
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 322, in get_members
    nodes = get_class_members(m, parent=parent)
  File "/home/oanwar/daliuge/daliuge/lib/python3.10/site-packages/dlg_paletteGen/module_base.py", line 51, in get_class_members
    ann = inspect.get_annotations(
  File "/usr/lib/python3.10/inspect.py", line 175, in get_annotations
    return_value = {key:
  File "/usr/lib/python3.10/inspect.py", line 176, in <dictcomp>
    value if not isinstance(value, str) else eval(value, globals, locals)
  File "<string>", line 1, in <module>
NameError: name 'Callable' is not defined. Did you mean: 'callable'?

**Comment by awicenec** [comment]
Please make sure to use astropy below version 6 for now. I'm not sure
whether the problem above is caused by this, but astropy introduced a few
really ugly coding and inheritance tricks and those are not supported yet.
